language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kepsic
  password:
    secure: iquYtIXcwQJy0LaXYOEzsfJ5eV/vwvrMbKPpmvR+bsKdB3+AngKnzxDLtEscMTg+Weo0ygMyb/+MSLMCGiXlsDLRYMCuE5tImnLNdkN9CrkA1UUlug9ySQg6I/JHoD4XP0GhfLYGUskbCwRm3skC75K3V94HgcmXGxf1T2NA8K5z/DTBbc/XA74aLDMQ96gE5JnFbHWbZb4ZfMMNGVi1eCsyCylqCfy6dY4B1vpJPha2azO5uCMPaVAk5prrAeyDUU+TS6ULygxfAN7WvHQwjImsScRQ3/ZIDUjPz+DbKwjYXNFQ3CXlX1nvJDQSDibWIn8Pb54Z3hovUiZxtIu23znhleDT7CAHYzrggmACG7st5MJBWs8uUbIS4mUd0is7CcPNjYMJtrlvNzIVG3FsYnMA6qDNE+ZQdEOBvilMvz43/CK7HKRJp8ZWISRJmuMRIGct4+JxOn0gLPiI9qS5SEEDhXohFJgg6vrpt1pcoPDIFqPJmf56ZWCWCW2hPJ6rPatMl6AUhcq6kFbRnBDp2nguJL1FvxtAR67UbDphvKtBS4M11TDR2VQTp+eb6nOAuf8uqFnmE6idAiNoCWn7wxA/arRt+d2bO22XCzhzHhrVwfuCkh4iQW9x8okkR/0VC3cEDlDiX+O3eFF+hsrIHWO9/KQgdJ+ja2htVxb5S28=
  on:
    tags: true
    repo: kepsic/moitoi_docker_hive
    python: 3.8
