language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mdh
  password:
    secure: EdDhkHRWkFhe0ykDMfTNRwS9Bb+08i8fD7WN+5+K4IPRDOIm2tmqwMYGuc4OAUN5Kj3qOzcZykkB+twgTpgScoTQOjtsMz90vIOng9X1CVbErCBhwSKkcaRgPfDojXFXOdz4gpAPPZ90OziM63RcsjBoySnYGtoZuWTvUrGpuZVPnemE/Pbnet7BC1um7ZvTzjuW0KF7P8b5SQHZEHfZkmzr4MJb5H23KyKkNInVuVfqS1FMM/2LyL41BGfVpjxiHuldXcEpA5IuA3uCiQw+j5tyhr4SwDb0zZq8Hrj1+06IB6l62cfvxJotNYLlsSvvl3/15JLfJNIMRgCmiKusGqt7g0Jkb+RiDbHh366DScG5te7gINfxA7HbPoeOuhDqM7jlaNtPK7xU8z1Q7QFQcbFU44yykR9/oFVThfmogRhC0YzgvPMJvmFx7idoB3V+0f+RMSeaHNdFvAHEdHnlSVb6IR36/sU/XkVQ9/jB0/Xx4IDY+5cHZIDELtCnHgQXRFEmeJxZ6Dxh0FDEVIJOl7FUU/QKS1HmU1S8D+cPPE3ZnyCUWXl7zlWTzpOC6V/Su4NJx8+CvZfHVjDlAxPAMUjUwDjeW//Q4UNI6Y55vPvjvTMaAlIRJrGvyoAE+obqWTbk9a2NzN7XlHSYy2+n08Q9FVTOawGa3KHdm2a7e4k=
  on:
    tags: true
    repo: kepsic/moitoi_docker_hive
    python: 3.8
